[project]
name = "youssouf-pipeline"
version = "0.1.0"
description = "Pipeline MLOps modulaire Youssouf"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyyaml>=6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/youssouf_pipeline"]
